[package]
name = "bigfoot-sim"
version = "0.2.0"
edition = "2021"
license = "CC0-1.0"

[profile.dev]
overflow-checks = false

[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = false

[dependencies]
bytemuck = "1.14.0"
rayon = "1.8.0"
